OrganicFoodMVC/Areas/Admin/Controllers/BrandController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OrganicFoodMVC.DataAccess.Repository.IRepository;
using OrganicFoodMVC.Models;
using OrganicFoodMVC.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OrganicFoodMVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class BrandController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public BrandController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            return View();
        }

        // insert and update
        public IActionResult Upsert(int? id)
        {
            Brand brand = new Brand();
            if(id == null)
            {
                // this is for create
                return View(brand);
            }

            //this is for edit
            brand = _unitOfWork.Brand.Get(id.GetValueOrDefault());
            if(brand == null)
            {
                return NotFound();
            }
            return View(brand);
        }

        // insert and update
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Brand brand)
        {
            if (ModelState.IsValid)
            {
                if(brand.Id == 0)
                {
                    _unitOfWork.Brand.Add(brand); // insert
                }
                else
                {
                    _unitOfWork.Brand.Update(brand); // update
                }
                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(brand);
        }

        #region API CALLS

        // api get
        [HttpGet]
        public IActionResult GetAll()
        {
            var allObj = _unitOfWork.Brand.GetAll();
            return Json(new { data = allObj });
        }

        // api delete
        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var objFromDb = _unitOfWork.Brand.Get(id);
            if(objFromDb == null)
            {
                return Json(new { success = false, message = "Xóa thất bại!" });
            }
            _unitOfWork.Brand.Remove(objFromDb);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Xóa thành công!" });
        }

        #endregion
    }
}

OrganicFoodMVC/Areas/Admin/Controllers/CompanyController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OrganicFoodMVC.DataAccess.Repository.IRepository;
using OrganicFoodMVC.Models;
using OrganicFoodMVC.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OrganicFoodMVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
    public class CompanyController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CompanyController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            return View();
        }

        // insert and update
        public IActionResult Upsert(int? id)
        {
            Company company = new Company();
            if (id == null)
            {
                // this is for create
                return View(company);
            }

            //this is for edit
            company = _unitOfWork.Company.Get(id.GetValueOrDefault());
            if (company == null)
            {
                return NotFound();
            }
            return View(company);
        }

        // insert and update
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Company company)
        {
            if (ModelState.IsValid)
            {
                if (company.Id == 0)
                {
                    _unitOfWork.Company.Add(company); // insert
                }
                else
                {
                    _unitOfWork.Company.Update(company); // update
                }
                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(company);
        }

        #region API CALLS

        // api get company
        [HttpGet]
        public IActionResult GetAll()
        {
            var allObj = _unitOfWork.Company.GetAll();
            return Json(new { data = allObj });
        }

        //api delete company
        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var objFromDb = _unitOfWork.Company.Get(id);
            if (objFromDb == null)
            {
                return Json(new { success = false, message = "Xóa thất bại!" });
            }
            _unitOfWork.Company.Remove(objFromDb);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Xóa thành công!" });
        }

        #endregion
    }
}

OrganicFoodMVC/Areas/Admin/Controllers/UnitController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OrganicFoodMVC.DataAccess.Repository.IRepository;
using OrganicFoodMVC.Models;
using OrganicFoodMVC.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OrganicFoodMVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class UnitController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public UnitController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            return View();
        }

        // show insert and update
        public IActionResult Upsert(int? id)
        {
            Unit unit = new Unit();
            if (id == null)
            {
                // this is for create
                return View(unit);
            }

            //this is for edit
            unit = _unitOfWork.Unit.Get(id.GetValueOrDefault());
            if (unit == null)
            {
                return NotFound();
            }
            return View(unit);
        }

        // insert and update
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Unit unit)
        {
            if (ModelState.IsValid)
            {
                if (unit.Id == 0)
                {
                    _unitOfWork.Unit.Add(unit); // insert
                }
                else
                {
                    _unitOfWork.Unit.Update(unit); // update
                }
                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(unit);
        }

        #region API CALLS

        // api get unit
        [HttpGet]
        public IActionResult GetAll()
        {
            var allObj = _unitOfWork.Unit.GetAll();
            return Json(new { data = allObj });
        }

        //api delete unit
        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var objFromDb = _unitOfWork.Unit.Get(id);
            if (objFromDb == null)
            {
                return Json(new { success = false, message = "Xóa thất bại!" });
            }
            _unitOfWork.Unit.Remove(objFromDb);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Xóa thành công!" });
        }

        #endregion
    }
}

OrganicFoodMVC/Areas/Admin/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OrganicFoodMVC.DataAccess.Data;
using OrganicFoodMVC.DataAccess.Repository.IRepository;
using OrganicFoodMVC.Models;
using OrganicFoodMVC.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OrganicFoodMVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _db;

        public UserController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            return View();
        }

        

        #region API CALLS

        // api get user
        [HttpGet]
        public IActionResult GetAll()
        {
            var userList = _db.ApplicationUsers.Include(u=>u.Company).ToList();

            var userRole = _db.UserRoles.ToList();
            var roles = _db.Roles.ToList();
            
            foreach(var user in userList)
            {
                var roleId = userRole.FirstOrDefault(u => u.UserId == user.Id).RoleId;
                user.Role = roles.FirstOrDefault(u => u.Id == roleId).Name;
                if(user.Company == null)
                {
                    user.Company = new Company()
                    {
                        Name = ""
                    };
                }    
            }    

            return Json(new { data = userList });
        }

        [HttpPost]
        public IActionResult LockUnlock([FromBody] string id)
        {
            var objFromDb = _db.ApplicationUsers.FirstOrDefault(u => u.Id == id);
            if(objFromDb == null)
            {
                return Json(new { success = false, message = "Lỗi không thể khóa!" });
            }
            if(objFromDb.LockoutEnd != null && objFromDb.LockoutEnd > DateTime.Now)
            {
                // user is currently locked, will unlock them
                objFromDb.LockoutEnd = DateTime.Now;
            }
            else
            {
                objFromDb.LockoutEnd = DateTime.Now.AddYears(1000);
            }
            _db.SaveChanges();
            return Json(new { success = true, message = "Thành công!" });
        }

        #endregion
    }
}

OrganicFoodMVC/Views/Shared/_CreateAndBackToListButton.cshtml
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control">Tạo Mới</button>
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control">Trở Về</a>
    </div>
</div>

OrganicFoodMVC/Views/Shared/_EditAndBackToListButton.cshtml
@model int
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control" asp-route-id="@Model">Cập Nhập</button>
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control">Trờ Về</a>
    </div>
</div>

OrganicFoodMVC/Views/Shared/_Layout.cshtml
@using OrganicFoodMVC.Utility
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="pragma" content="no-cache" />
    <meta http-equiv="cache-control" content="max-age=604800" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>@ViewData["Title"] - Organic Food</title>

    <link rel="icon" href="~/images/icon/Logo.png" type="image/x-icon">
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />*@
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/Assets/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="~/Assets/css/jquery-ui.min.css" />
    <link rel="stylesheet" href="~/Assets/css/toastr.min.css" />
    <script src="~/Assets/js/jquery.min.js"></script>

    <!-- Bootstrap4 files-->
    <link href="~/Assets/css/bootstrap.css" rel="stylesheet" type="text/css" />

    <!-- Font awesome 5 -->
    <link href="~/Assets/fonts/fontawesome/css/all.min.css" type="text/css" rel="stylesheet">

    <!-- custom style -->
    <link href="~/Assets/css/ui.css" rel="stylesheet" type="text/css" />
    <link href="~/Assets/css/responsive.css" rel="stylesheet" type="text/css" />

</head>
<body>

    <header class="section-header">
        <section class="header-main border-bottom">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-xl-2 col-lg-3 col-md-12">
                        <a class="brand-wrap" asp-area="" asp-controller="Home" asp-action="Index">
                            <img class="logo" src="~/Assets/images/logo.png">
                        </a> <!-- brand-wrap.// -->
                    </div>
                    <div class="col-xl-6 col-lg-5 col-md-6">
                        @*<form action="#" class="search-header">
                                <div class="input-group w-100">
                                    <select class="custom-select border-right" name="category_name">
                                        <option value="">Tất cả</option>
                                        <option value="comments">Rau xanh</option>
                                        <option value="content">Hoa quả</option>
                                    </select>
                                    <input type="text" class="form-control" placeholder="Nhập sản phẩm cần tìm">

                                    <div class="input-group-append">
                                        <button class="btn btn-primary" type="submit">
                                            <i class="fa fa-search"></i> Tìm kiếm
                                        </button>
                                    </div>
                                </div>
                            </form>*@ <!-- search-wrap .end// -->
                        @await Component.InvokeAsync("Search")

                    </div> <!-- col.// -->
                    <div class="col-xl-4 col-lg-4 col-md-6">
                        <div class="widgets-wrap float-md-right">

                            @*<div class="widget-header mr-3">
                                    <a href="#" class="widget-view">
                                        <div class="icon-area">
                                            <i class="fa fa-user"></i>
                                            <span class="notify">3</span>
                                        </div>
                                        <small class="text"> Thông tin </small>
                                    </a>
                                </div>*@

                            <partial name="_LoginPartial" />

                            @if (User.IsInRole(SD.Role_Admin))
                            {
                                <div class="widget-header mr-3">
                                    <a asp-area="Admin" asp-controller="Order" asp-action="index" class="widget-view">
                                        <div class="icon-area">
                                            <i class="fa fa-store"></i>
                                        </div>
                                        <small class="text"> Hóa đơn </small>
                                    </a>
                                </div>
                            } else if (User.IsInRole(SD.Role_User_Indi)) 
                            { 
                                <div class="widget-header mr-3">
                                    <a asp-area="Customer" asp-controller="Order" asp-action="index" class="widget-view">
                                        <div class="icon-area">
                                            <i class="fa fa-store"></i>
                                        </div>
                                        <small class="text"> Hóa đơn </small>
                                    </a>
                                </div>
                            }

                            @if (HttpContextAccessor.HttpContext.Session.GetInt32(SD.ssShoppingCart) != null)
                            {
                                <div class="widget-header">
                                    <a asp-area="Customer" asp-controller="Cart" asp-action="Index" class="widget-view">
                                        @{
                                            var count = HttpContextAccessor.HttpContext.Session.GetInt32(SD.ssShoppingCart);
                                        }
                                        <div class="icon-area">
                                            <i class="fa fa-shopping-cart"></i>
                                            <span class="notify">@count</span>
                                        </div>
                                        <small class="text"> Giỏ hàng </small>
                                    </a>
                                </div>
                            }
                            else
                            {
                                <div class="widget-header">
                                    <a asp-area="Customer" asp-controller="Cart" asp-action="Index" class="widget-view">
                                        <div class="icon-area">
                                            <i class="fa fa-shopping-cart"></i>
                                            <span class="notify">0</span>
                                        </div>
                                        <small class="text"> Giỏ hàng </small>
                                    </a>
                                </div>
                            }
                        </div> <!-- widgets-wrap.// -->
                    </div> <!-- col.// -->
                </div> <!-- row.// -->
            </div> <!-- container.// -->
        </section> <!-- header-main .// -->


        <nav class="navbar navbar-main navbar-expand-lg border-bottom">
            <div class="container">

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main_nav" aria-controls="main_nav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="main_nav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Trang chủ</a>
                        </li>
                        @*<li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#"> <i class="fa fa-bars text-muted mr-2"></i> Thể loại </a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-area="Customer" asp-controller="Category" asp-action="Index">Rau xanh</a>
                                </div>
                            </li>*@

                        @*Menu category*@
                        @await Component.InvokeAsync("MenuCategory")

                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Quản lý nội dung
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Loại sản phẩm</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Brand" asp-action="Index">Thương hiệu</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Sản phẩm</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Unit" asp-action="Index">Đơn vị tính</a>
                                </div>
                            </li>
                        }
                        @if (User.IsInRole(SD.Role_Admin) || User.IsInRole(SD.Role_Employee))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Quản lý người dùng
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="User" asp-action="Index">Tài khoản người dùng</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Nhà bán hàng</a>
                                </div>
                            </li>
                        }

                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Thông tin liên hệ</a>
                        </li>
                    </ul>

                    @*<ul class="navbar-nav ml-md-auto">
                            <li class="nav-item dropdown">
                                <partial name="_LoginPartial" />

                            </li>
                        </ul>*@

                </div> <!-- collapse .// -->
            </div> <!-- container .// -->
        </nav>
    </header> <!-- section-header.// -->

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!-- ========================= FOOTER ========================= -->
    <footer class="section-footer bg-secondary">
        <div class="container">
            <section class="footer-bottom text-center">
                <p class="text-white">Thực phẩm sạch - Tươi ngon</p>
                <p class="text-muted"> &copy 2023 Nhóm 4 Organic Food</p>
                <br>
            </section>
        </div><!-- //container -->
    </footer>
    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@
    <!-- jQuery -->
    <script src="~/Assets/js/jquery-2.0.0.min.js" type="text/javascript"></script>

    <!-- Bootstrap4 files-->
    <script src="~/Assets/js/bootstrap.bundle.min.js" type="text/javascript"></script>

    <!-- custom javascript -->
    <script src="~/Assets/js/script.js" type="text/javascript"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/Assets/js/jquery-ui.min.js"></script>
    <script src="~/Assets/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="~/Assets/js/toastr.min.js"></script>
    <script src="~/Assets/js/sweetalert.min.js"></script>
    <script src="~/Assets/js/e19c476714.js"></script>
    <script src="~/Assets/js/ellipsis.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>